### ISSUE TITLE
feature/FileOpenLink

### ISSUE THREAD

**Issue by baza-trainee** [baza-trainee/ataka-help-front-end#53]
1. Додати пропс, який дозволяє ще окремо стилізувати лінк в плашці кукіс.
2. Зробити адаптивну верстку лінка

**Comment by KonstantinLigus** [comment]
Я в одній гілці дві фічі зробив

**Comment by KonstantinLigus** [comment]
Додав можливість задавати три шляхи для pdf файлу для різних екранів
